KYLIN: scripts/backport-tools: improve test-commit-in-tree error handling
Mainline: KYLIN-only
Severity: Low

Modernize argument parsing and fix return value logic in the
test-commit-in-tree script. Replace deprecated syntax with proper
error checking and variable quoting. Add color support and consistent
exit codes. Rename function to follow naming conventions.

K2CI-Arch: All
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I71ce8e0f0dc36cd4284067251cb5be958681a737
Reviewed-on: https://code.kylinos.cn:443/c/institute/kernel/klinux/+/93345
Tested-by: kernel-bot <kernel-bot@kylinos.cn>

diff --git a/scripts/backport-tools/test-commit-in-tree b/scripts/backport-tools/test-commit-in-tree
--- a/scripts/backport-tools/test-commit-in-tree
+++ b/scripts/backport-tools/test-commit-in-tree
@@ -1,12 +1,11 @@
 #!/bin/bash
 
-. $(dirname $0)/init-functions
+. "$(dirname "$0")/init-functions"
 
 BRANCH_COMMIT=HEAD
 
-function usage()
-{
-	echo -e "`basename $0` [OPTION]... upstream-commit-id"
+usage() {
+	echo -e "$(basename "$0") [OPTION]... upstream-commit-id"
 	echo
 	echo -e "  -h, --help\t\t\tshow this help info"
 	echo -e "  -q, --quiet\t\t\tdo not print tips"
@@ -14,75 +13,111 @@ function usage()
 	echo
 }
 
-function commit-in-tree()
-{
-	fullhash=$(git rev-parse $1)
-	# This might happen if someone pointed to a commit that doesn't exist in our
-	# tree.
-	if [ "$?" -gt "0" ]; then
+commit_in_tree() {
+	local commit="$1"
+	local fullhash
+	local subj
+	local stable_maj_ver
+	local stable_min_ver
+	local cursubj
+	local i
+
+	# Validate input
+	if [[ -z "$commit" ]]; then
+		echo -e "${YELLOW}Warning: No commit specified${NC}" >&2
+		return 0
+	fi
+
+	# Get full hash of the commit
+	if ! fullhash=$(git rev-parse "$commit" 2>/dev/null); then
+		# This might happen if someone pointed to a commit that doesn't exist in our tree
 		return 0
 	fi
 
 	# Hope for the best, same commit is/isn't in the current branch
-	if git merge-base --is-ancestor $fullhash $BRANCH_COMMIT; then
+	if git merge-base --is-ancestor "$fullhash" "$BRANCH_COMMIT" 2>/dev/null; then
 		return 1
 	fi
 
 	# Grab the subject, since commit sha1 is different between branches we
-	# have to look it up based on subject.
-	subj=$(git log -1 --pretty="%s" $1)
-	if [ $? -gt 0 ]; then
+	# have to look it up based on subject
+	if ! subj=$(git log -1 --pretty="%s" "$commit" 2>/dev/null); then
 		return 0
 	fi
 
-	STABLE_MAJ_VER=$(git --no-pager blame $BRANCH_COMMIT -s -L 1,3 $SOURCE_ROOT/Makefile | \
-			 grep VERSION | head -n1 | awk {'print $5'})
-	STABLE_MIN_VER=$(git --no-pager blame $BRANCH_COMMIT -s -L 1,3 $SOURCE_ROOT/Makefile | \
-			 grep PATCHLEVEL | head -n1 | awk {'print $5'})
+	# Use version information from init-functions
+	if [[ -z "$STABLE_MAJ_VER" ]] || [[ -z "$STABLE_MIN_VER" ]]; then
+		echo -e "${YELLOW}Warning: Could not determine version information${NC}" >&2
+		return 0
+	fi
+
+	stable_maj_ver="$STABLE_MAJ_VER"
+	stable_min_ver="$STABLE_MIN_VER"
 
 	# Try and find if there's a commit with given subject the hard way
-	for i in $(git log --pretty="%H" -F --grep "$subj" v$STABLE_MAJ_VER.$STABLE_MIN_VER..$BRANCH_COMMIT); do
-		cursubj=$(git log -1 --format="%s" $i)
-		if [ "$cursubj" = "$subj" ]; then
-			return 1
+	while IFS= read -r i; do
+		if [[ -n "$i" ]]; then
+			if cursubj=$(git log -1 --format="%s" "$i" 2>/dev/null); then
+				if [[ "$cursubj" == "$subj" ]]; then
+					return 1
+				fi
+			fi
 		fi
-	done
+	done < <(git log --pretty="%H" -F --grep "$subj" "v${stable_maj_ver}.${stable_min_ver}..${BRANCH_COMMIT}" 2>/dev/null)
+
 	return 0
 }
 
-ARGS=`getopt -o hqb: -a --long help,quiet,branch: -- "$@"`
-[ $? != 0 ] && echo "Terminating..." && usage && exit -1
+# Parse command line arguments
+if ! ARGS=$(getopt -o hqb: -a --long help,quiet,branch: -- "$@"); then
+	echo "Terminating..." >&2
+	usage
+	exit 1
+fi
 
 eval set -- "${ARGS}"
 
-while true
-do
-	case $1 in
+while true; do
+	case "$1" in
 		-h|--help)
 			usage
-			exit 1;;
+			exit 0
+			;;
 		-b|--branch)
-			BRANCH_COMMIT=$2
-			shift 2;;
+			BRANCH_COMMIT="$2"
+			shift 2
+			;;
 		-q|--quiet)
 			QUIET_TIPS=true
-			shift;;
+			shift
+			;;
 		--)
 			shift
-			break;;
+			break
+			;;
+		*)
+			echo -e "${YELLOW}Unknown option: $1${NC}" >&2
+			usage
+			exit 1
+			;;
 	esac
 done
 
-# check args
-[ $# -lt 1 ] && usage && exit -1
+# Check arguments
+if [[ $# -lt 1 ]]; then
+	echo -e "${YELLOW}Error: Missing upstream-commit-id argument${NC}" >&2
+	usage
+	exit 1
+fi
 
-# check
-commit-in-tree $1
+# Main logic
+commit_in_tree "$1"
+result=$?
 
-if [[ $? == 1 ]]; then
-	[ x"$QUIET_TIPS" != x"true" ] && echo -e "\033[32mFound.\033[0m"
+if [[ $result -eq 1 ]]; then
+	[[ "$QUIET_TIPS" != "true" ]] && echo -e "${GREEN}Found.${NC}"
 	exit 0
 else
-	[ x"$QUIET_TIPS" != x"true" ] && echo -e "\033[34mNot Found.\033[0m"
+	[[ "$QUIET_TIPS" != "true" ]] && echo -e "${BLUE}Not Found.${NC}"
 	exit 1
 fi
